apiVersion : apps/v1
kind: Deployment
metadata:
  name: "startstopdemo-687f"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "startstopdemo-687f"
  template:
    metadata:
      labels:
        app: "startstopdemo-687f"
    spec:
      containers:
        - name: "startstopdemo-687f"
          image: "testrg12.azurecr.io/startstopdemo"
          ports:
          - containerPort: 80