apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubecondemo-850f"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubecondemo-850f"
  template:
    metadata:
      labels:
        app: "kubecondemo-850f"
    spec:
      containers:
        - name: "kubecondemo-850f"
          image: "kubecondemorg.azurecr.io/kubecondemo"
          ports:
          - containerPort: 80